# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-03-15 13:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailToken',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Email Token')),
                ('email', models.EmailField(max_length=100, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='email_token',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='watched_by',
            field=models.ManyToManyField(blank=True, related_name='watching', to=settings.AUTH_USER_MODEL),
        ),
    ]
