# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-03-23 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200316_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='forgot_pass_token',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
